### ISSUE TITLE
Para usar eu troco o pcl345.py que vem em pkpgcounter/pkpgpdls pelo pcl345.py do seu repositório.

### ISSUE THREAD

**Issue by thiagogomesverissimo** [wgnann/pkpghack#1]
E instalo as dependências, correto?

**Comment by wgnann** [comment]
Quando eu escrevi o scriptzinho, ele já corria atrás das dependências. Mas não garanto que esteja funcionando hoje em dia.

**Comment by thiagogomesverissimo** [comment]
As dependências ok, eu olhei e são fáceis de instalar.
Mas vc usa o código em si para contabilizar as páginas em produção?
