### ISSUE TITLE
Vocês tiveram problemas com a contagem de páginas de arquivos docx?

### ISSUE THREAD

**Issue by thiagogomesverissimo** [wgnann/pkpghack#2]

**Comment by thiagogomesverissimo** [comment]
Quando instalamos o drive PostScript nos computadores dos usuários o documento enviado para impressão não é convertido para ps e depois o cups manda para o pykota q vai fazer a contagem com o pkpgcounter. É esse o fluxo?

**Comment by wgnann** [comment]
Pelos testes que fizemos, no Windows, é isso que ocorre. Contudo, no Linux, é possível que alguns arquivos sejam mandados diretamente para a fila de impressão (e.g. lpr).
